### ISSUE TITLE
(Suggestion) Add the wheel zoom without CTRL

### ISSUE THREAD

**Issue by happysurf** [sblask/webextension-enhanced-image-viewer#1]
The wheel zoom is possible with CRTL key but in my opinion is better and more immediate for any user use only the mouse wheel for zooming the image.
Thanks.

**Comment by sblask** [comment]
So you want this to behave exactly the same way as ctrl-scroll? I don't see too much value in that. Or do you have something else in mind? Also, if I'd do this, this would have to be optional(as in an option that is disabled by default) as I want to keep the ability to scroll...

**Comment by happysurf** [comment]
For me the better way for manage an image is > "view image" and then start to zoom with mouse wheel by default.
All others options are good but interesting for advanced users.
In addition in other addons like Wiewhance and Better Image Viewer the wheel mouse works alone without any key because simple is better.
Of course this is only a my opinion.

**Comment by sblask** [comment]
I just checked Viewhance, it says "Mouse wheel zooming (off by default)" I think if I'd do that, I would do the same. But you would have to enable that only once. I didn't try Better Image Viewer, is it using the browser zoom? Because I could also implement my own zoom. The advantage would be that the zoom would be unlimited whereas the browser zoom stops at 2x or 3x. But I am not sure how that should work with the different fitting modes... Should zooming only work in "Natural Size" mode? When someone tries to zoom in a different mode, should I just "switch" or should it be disabled? The rotation is also fairly complicated...

**Comment by happysurf** [comment]
All extensions tried in the past including the old legacy types use infinite zoom and not the browser one.
Activate the wheel zoom with an option (on or off like Viewhance) is good for me.
For me is better active because if I want see a photo detail the simple way is zoom in with mouse and not select a particular mode.
Infinite zoom must works with all your modes (like in Better Image Viewer) for that I think is not a problem.
If I want rotate an image this is the first thing that I do, then decide if zoom the image or not, for that this must be possible in natural size only.

**Comment by sblask** [comment]
I'll see what I can do, but it will take a while. I've got another extension that I need to migrate to the webextension API first...

**Comment by sblask** [comment]
Realistically this is not going to happen unless someone provides a patch. I don't even have time to do minor things in my other extensions. I close this until someone provides a patch.
