### ISSUE TITLE
Feature request: Left click hold drag/pan functionality

### ISSUE THREAD

**Issue by Hexerin** [sblask/webextension-enhanced-image-viewer#6]
So this is a new feature request and an existing feature adjustment request in one.

First, I would request the new feature that left click and hold allows the image to be dragged/panned freely. This is extremely useful functionality, yet is missing in 99% of image viewers for some insane reason.

Second, I would request that the existing left click to cycle between scaling modes be adjusted to CTRL+left click instead. Would make more sense this way if left click hold to drag/pan functionality is added.

**Comment by sblask** [comment]
I don't have time to implement new features, but there are other extensions that you could combine with this one to get dragging to work. ScrollAnywhere for example. It still changes the mode after dragging because the browser seems to think it's still a click, but I think that could be something that could be fixed on the drag extension side.
